version: 0.2
env:
  variables:
    SONAR_PROJECT_KEY: "x23200863cdos_sonar"
    SONAR_ORGANIZATION: "x23200863cdos"
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_TOKEN: "ecf12a1ce3448f871d7d60dfc95d36f2a9ae43a2"

phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.11  # Use a supported Python version
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
      - pip install --upgrade pip
      - pip install pylint
      - pip install -r requirements.txt

  pre_build:
    commands:
      - python --version
      - pylint --disable=all --enable=C,R,F,W $CODEBUILD_SRC_DIR/*.py
      - pylint --disable=all --enable=C,R,F,W $CODEBUILD_SRC_DIR/**/*.py
      - pylint --disable=C0303,C0301 $CODEBUILD_SRC_DIR/artshifu/*.py

  build:
    commands:
      - mvn test     
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi

artifacts:
  files:
    - '**/*'
